#!/bin/bash

#DEBHELPER#

# postrm script for mx-system

#set -e

case "$1" in
  purge|remove) dpkg-divert --quiet                                               \
                            --remove                                              \
                            --package mxrpi-docs               \
                            --rename                                              \
                            --divert /usr/share/applications/xvkbd.desktop.dpkg-dist \
                             /usr/share/applications/xvkbd.desktop
                ;;

             *) :
                ;;
esac 

exit 0
